tasks:
 - init: >
        sudo apt update &&
        sleep 2 &&
        sudo apt install zstd shellcheck &&
        sleep 2 &&
        pip install torch -index-url https://download.pytorch.org/whl/cpu &&
        sleep 2 &&
        pip install onnx &&
        sleep 2 &&
        echo "done"
